# Generated by Django 5.0.4 on 2024-05-11 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OS', 'Oatside Series'), ('NB', 'Non-Coffe Beverage'), ('LS', 'Latte Series'), ('AS', 'Aren Series'), ('BS', 'Bakery Series')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('kembangan', 'kembangan'), ('Menteng', 'Menteng'), ('Cakung', 'Cakung'), ('Cengkareng', 'Cengkareng'), ('Cilandak', 'Cilandak'), ('Cilincing', 'Cilincing'), ('Cipayung', 'Cipayung'), ('Ciracas', 'Ciracas'), ('Duren Sawit', 'Duren Sawit'), ('Gambir', 'Gambir'), ('Grogol Petamburan', 'Grogol Petamburan'), ('Jagakarsa', 'Jagakarsa'), ('Jatinegara', 'Jatinegara'), ('Johar Baru', 'Johar Baru'), ('Kalideres', 'Kalideres'), ('Kebayoran Baru', 'Kebayoran Baru'), ('Kebayoran Lama', 'Kebayoran Lama'), ('Kebon Jeruk', 'Kebon Jeruk'), ('Kelapa Gading', 'Kelapa Gading'), ('Kemayoran', 'Kemayoran')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
